### ISSUE TITLE
UnicodeDecode error

### ISSUE THREAD

**Issue by gvangool** [simonw/symbex#17]
I tried it on my $WORK project, which includes the venv directory as a subdirectory of the main repo.

I get the following error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 81: invalid start byte
```

It looks like it came from IPython (the errored file is `.venv/lib/python3.11/site-packages/IPython/core/tests/nonascii.py`), looking at the encoding:
```
$ file .venv/lib/python3.11/site-packages/IPython/core/tests/nonascii.py
.venv/lib/python3.11/site-packages/IPython/core/tests/nonascii.py: ISO-8859 text
```

**Comment by spookylukey** [comment]
This is another place where you could probably benefit from the work done in pyastgrep, as mentioned [here](https://github.com/simonw/symbex/issues/15#issuecomment-1597456924)

**Comment by simonw** [comment]
Hah I just hit that one myself:
- #18
